/**
 * Community spawn weights (PoE2DB) as weight tables of the production dataset.
 *
 * `poe2db-weights.json` is generated by scripts/data/weights-normalize.ts and never edited by hand.
 * One PoE2DB page = one table = one group of bases (a class, or a class with an attribute tag).
 * A base reads weights from its own table only; a modifier absent from it or listed as unmeasured
 * keeps an unknown weight there.
 */
import type { ItemBase, WeightEvidence, WeightTable } from '@poe2-craft/craft-domain';
import weightsFile from './poe2db-weights.json';
import { WEIGHTS_SOURCE_ID } from './rules';

export interface WeightsFileTable {
  readonly id: string;
  readonly page: string;
  readonly itemClassId: string;
  readonly tag: string | null;
  readonly requiredTags: readonly string[];
  readonly url: string;
  readonly rows: number;
  readonly entries: readonly { modifierId: string; weight: number; rawValue: string }[];
  readonly unmeasured: readonly string[];
  readonly bases: readonly string[];
}

export interface WeightsFile {
  readonly gamePatch: string | null;
  readonly gameVersion: string;
  readonly capturedAt: string;
  readonly placeholderMax: number;
  readonly tables: readonly WeightsFileTable[];
  readonly unassigned: readonly { baseId: string; name: string; itemClassId: string; reason: string }[];
  readonly conflicts: readonly { page: string; modifierId: string; values: readonly string[] }[];
  readonly unresolved: readonly { page: string; name: string; reason: string }[];
}

export const PRODUCTION_WEIGHTS = weightsFile as unknown as WeightsFile;

/** Evidence shared by every weight of one table: source, method, capture date, patch and group. */
export function tableEvidence(table: Pick<WeightsFileTable, 'page' | 'tag'>, file: Pick<WeightsFile, 'capturedAt' | 'gamePatch'>): WeightEvidence {
  return {
    sourceId: WEIGHTS_SOURCE_ID,
    method: 'recombinator-observation',
    confidence: 'community',
    capturedAt: file.capturedAt.slice(0, 10),
    ...(file.gamePatch ? { patch: file.gamePatch } : {}),
    normalized: false,
    context: `PoE2DB ${table.page}${table.tag ? ` (bases tagged ${table.tag})` : ''}`,
  };
}

export function weightTables(file: WeightsFile, gameVersion: string): WeightTable[] {
  return file.tables.map((t) => ({
    id: t.id,
    title: `PoE2DB ${t.page.replace(/_/g, ' ')}`,
    itemClassId: t.itemClassId,
    requiredTags: t.requiredTags,
    entries: t.entries,
    unmeasured: t.unmeasured,
    evidence: tableEvidence(t, file),
    versions: { introducedIn: gameVersion },
  }));
}

/** Bases with their table. A base listed by two tables is a broken file: it fails loudly. */
export function assignWeightTables(bases: readonly ItemBase[], file: WeightsFile): ItemBase[] {
  const tableOf = new Map<string, string>();
  for (const table of file.tables) for (const baseId of table.bases) {
    if (tableOf.has(baseId)) throw new Error(`weights: base ${baseId} is in two tables`);
    tableOf.set(baseId, table.id);
  }
  return bases.map((base) => {
    const weightTableId = tableOf.get(base.id);
    return weightTableId ? { ...base, weightTableId } : base;
  });
}
