/**
 * Local copies of game art, keyed by the art id the CraftDB records carry (`ItemBase.artAssetId`,
 * `Consumable.art`). The domain only stores the id; this manifest is the infrastructure side that
 * knows where each image lives and where it came from.
 *
 * Every file was downloaded once (2026-10-02) from GGG's CDN, through the official PoE 2 trade
 * data (`official.trade2-data`) or the item JSON of trade listings (`official.trade2-listings`),
 * and is served by this site from /icons/game — never hotlinked. Images © Grinding Gear Games,
 * used in a non-commercial fan tool; check GGG's fan-site rules before a public launch.
 */
export interface ArtAsset {
  readonly file: string;
  /** Intrinsic size in pixels; images are shown at this size or smaller, never upscaled. */
  readonly width: number;
  readonly height: number;
  /** DataSource id the art was taken through. */
  readonly source: 'official.trade2-data' | 'official.trade2-listings';
  /** CDN address the copy was made from (attribution only, never requested by the site). */
  readonly origin: string;
}

export const ART_RETRIEVED = '2026-10-02';
export const ART_COPYRIGHT = '© Grinding Gear Games';

export const ART_MANIFEST: Readonly<Record<string, ArtAsset>> = {
  'Art/2DItems/Currency/CurrencyRerollRare': {
    file: 'CurrencyRerollRare.png',
    width: 64,
    height: 64,
    source: 'official.trade2-data',
    origin: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQ3VycmVuY3lSZXJvbGxSYXJlIiwic2NhbGUiOjEsInJlYWxtIjoicG9lMiJ9XQ/c0ca392a78/CurrencyRerollRare.png',
  },
  'Art/2DItems/Currency/CurrencyAddModToRare': {
    file: 'CurrencyAddModToRare.png',
    width: 64,
    height: 64,
    source: 'official.trade2-data',
    origin: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQ3VycmVuY3lBZGRNb2RUb1JhcmUiLCJzY2FsZSI6MSwicmVhbG0iOiJwb2UyIn1d/ad7c366789/CurrencyAddModToRare.png',
  },
  'Art/2DItems/Currency/CurrencyModValues': {
    file: 'CurrencyModValues.png',
    width: 64,
    height: 64,
    source: 'official.trade2-data',
    origin: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQ3VycmVuY3lNb2RWYWx1ZXMiLCJzY2FsZSI6MSwicmVhbG0iOiJwb2UyIn1d/2986e220b3/CurrencyModValues.png',
  },
  'Art/2DItems/Currency/Omens/VoodooOmens1Dark': {
    file: 'VoodooOmens1Dark.png',
    width: 64,
    height: 64,
    source: 'official.trade2-data',
    origin: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvT21lbnMvVm9vZG9vT21lbnMxRGFyayIsInNjYWxlIjoxLCJyZWFsbSI6InBvZTIifV0/2dea0999d5/VoodooOmens1Dark.png',
  },
  'Art/2DItems/Currency/Omens/VoodooOmens3Dark': {
    file: 'VoodooOmens3Dark.png',
    width: 64,
    height: 64,
    source: 'official.trade2-data',
    origin: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvT21lbnMvVm9vZG9vT21lbnMzRGFyayIsInNjYWxlIjoxLCJyZWFsbSI6InBvZTIifV0/6e2bb52963/VoodooOmens3Dark.png',
  },
  'Art/2DItems/Currency/Omens/VoodooOmens2Yellow': {
    file: 'VoodooOmens2Yellow.png',
    width: 64,
    height: 64,
    source: 'official.trade2-data',
    origin: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvT21lbnMvVm9vZG9vT21lbnMyWWVsbG93Iiwic2NhbGUiOjEsInJlYWxtIjoicG9lMiJ9XQ/6d316b47ee/VoodooOmens2Yellow.png',
  },
  'Art/2DItems/Currency/Omens/VoodooOmens3Yellow': {
    file: 'VoodooOmens3Yellow.png',
    width: 64,
    height: 64,
    source: 'official.trade2-data',
    origin: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvT21lbnMvVm9vZG9vT21lbnMzWWVsbG93Iiwic2NhbGUiOjEsInJlYWxtIjoicG9lMiJ9XQ/ed7cf06fa4/VoodooOmens3Yellow.png',
  },
  'Art/2DItems/Weapons/OneHandWeapons/OneHandSpears/1HSpear10': {
    file: '1HSpear10.png',
    width: 47,
    height: 188,
    source: 'official.trade2-listings',
    origin: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvV2VhcG9ucy9PbmVIYW5kV2VhcG9ucy9PbmVIYW5kU3BlYXJzLzFIU3BlYXIxMCIsInciOjEsImgiOjQsInNjYWxlIjoxLCJyZWFsbSI6InBvZTIifV0/114525ad0e/1HSpear10.png',
  },
  'Art/2DItems/Weapons/OneHandWeapons/OneHandSpears/1HSpear01': {
    file: '1HSpear01.png',
    width: 47,
    height: 188,
    source: 'official.trade2-listings',
    origin: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvV2VhcG9ucy9PbmVIYW5kV2VhcG9ucy9PbmVIYW5kU3BlYXJzLzFIU3BlYXIwMSIsInciOjEsImgiOjQsInNjYWxlIjoxLCJyZWFsbSI6InBvZTIifV0/84a2d1da16/1HSpear01.png',
  },
  'Art/2DItems/Weapons/OneHandWeapons/OneHandSpears/1HSpear03': {
    file: '1HSpear03.png',
    width: 47,
    height: 188,
    source: 'official.trade2-listings',
    origin: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvV2VhcG9ucy9PbmVIYW5kV2VhcG9ucy9PbmVIYW5kU3BlYXJzLzFIU3BlYXIwMyIsInciOjEsImgiOjQsInNjYWxlIjoxLCJyZWFsbSI6InBvZTIifV0/d4c8557684/1HSpear03.png',
  },
  'Art/2DItems/Weapons/OneHandWeapons/OneHandSpears/1HSpear05': {
    file: '1HSpear05.png',
    width: 47,
    height: 188,
    source: 'official.trade2-listings',
    origin: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvV2VhcG9ucy9PbmVIYW5kV2VhcG9ucy9PbmVIYW5kU3BlYXJzLzFIU3BlYXIwNSIsInciOjEsImgiOjQsInNjYWxlIjoxLCJyZWFsbSI6InBvZTIifV0/b176f54004/1HSpear05.png',
  },
  'Art/2DItems/Weapons/OneHandWeapons/OneHandSpears/1HSpear02': {
    file: '1HSpear02.png',
    width: 47,
    height: 188,
    source: 'official.trade2-listings',
    origin: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvV2VhcG9ucy9PbmVIYW5kV2VhcG9ucy9PbmVIYW5kU3BlYXJzLzFIU3BlYXIwMiIsInciOjEsImgiOjQsInNjYWxlIjoxLCJyZWFsbSI6InBvZTIifV0/08f2f8530e/1HSpear02.png',
  },
  'Art/2DItems/Weapons/TwoHandWeapons/Bows/Basetypes/Bow04': {
    file: 'Bow04.png',
    width: 94,
    height: 188,
    source: 'official.trade2-listings',
    origin: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvV2VhcG9ucy9Ud29IYW5kV2VhcG9ucy9Cb3dzL0Jhc2V0eXBlcy9Cb3cwNCIsInciOjIsImgiOjQsInNjYWxlIjoxLCJyZWFsbSI6InBvZTIifV0/fc5fb2ae18/Bow04.png',
  },
  'Art/2DItems/Weapons/TwoHandWeapons/Bows/Basetypes/Bow01': {
    file: 'Bow01.png',
    width: 94,
    height: 188,
    source: 'official.trade2-listings',
    origin: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvV2VhcG9ucy9Ud29IYW5kV2VhcG9ucy9Cb3dzL0Jhc2V0eXBlcy9Cb3cwMSIsInciOjIsImgiOjQsInNjYWxlIjoxLCJyZWFsbSI6InBvZTIifV0/30226ab5e1/Bow01.png',
  },
  'Art/2DItems/Weapons/TwoHandWeapons/Bows/Basetypes/Bow06': {
    file: 'Bow06.png',
    width: 94,
    height: 188,
    source: 'official.trade2-listings',
    origin: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvV2VhcG9ucy9Ud29IYW5kV2VhcG9ucy9Cb3dzL0Jhc2V0eXBlcy9Cb3cwNiIsInciOjIsImgiOjQsInNjYWxlIjoxLCJyZWFsbSI6InBvZTIifV0/b0a606586d/Bow06.png',
  },
  'Art/2DItems/Weapons/TwoHandWeapons/Bows/Basetypes/Bow09': {
    file: 'Bow09.png',
    width: 94,
    height: 188,
    source: 'official.trade2-listings',
    origin: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvV2VhcG9ucy9Ud29IYW5kV2VhcG9ucy9Cb3dzL0Jhc2V0eXBlcy9Cb3cwOSIsInciOjIsImgiOjQsInNjYWxlIjoxLCJyZWFsbSI6InBvZTIifV0/e62ea7f094/Bow09.png',
  },
  'Art/2DItems/Weapons/TwoHandWeapons/WarStaves/Warstaff01': {
    file: 'Warstaff01.png',
    width: 47,
    height: 189,
    source: 'official.trade2-listings',
    origin: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvV2VhcG9ucy9Ud29IYW5kV2VhcG9ucy9XYXJTdGF2ZXMvV2Fyc3RhZmYwMSIsInciOjIsImgiOjQsInNjYWxlIjoxLCJyZWFsbSI6InBvZTIifV0/fea458e458/Warstaff01.png',
  },
  'Art/2DItems/Weapons/TwoHandWeapons/WarStaves/Warstaff02': {
    file: 'Warstaff02.png',
    width: 47,
    height: 189,
    source: 'official.trade2-listings',
    origin: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvV2VhcG9ucy9Ud29IYW5kV2VhcG9ucy9XYXJTdGF2ZXMvV2Fyc3RhZmYwMiIsInciOjIsImgiOjQsInNjYWxlIjoxLCJyZWFsbSI6InBvZTIifV0/23459cf5a8/Warstaff02.png',
  },
  'Art/2DItems/Currency/CurrencyUpgradeToMagic': {
    file: 'CurrencyUpgradeToMagic.png',
    width: 64,
    height: 64,
    source: 'official.trade2-data',
    origin: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQ3VycmVuY3lVcGdyYWRlVG9NYWdpYyIsInNjYWxlIjoxLCJyZWFsbSI6InBvZTIifV0/2f8e1ff9f8/CurrencyUpgradeToMagic.png',
  },
  'Art/2DItems/Currency/CurrencyAddModToMagic': {
    file: 'CurrencyAddModToMagic.png',
    width: 64,
    height: 64,
    source: 'official.trade2-data',
    origin: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQ3VycmVuY3lBZGRNb2RUb01hZ2ljIiwic2NhbGUiOjEsInJlYWxtIjoicG9lMiJ9XQ/c8ad0ddc84/CurrencyAddModToMagic.png',
  },
  'Art/2DItems/Currency/CurrencyUpgradeToRare': {
    file: 'CurrencyUpgradeToRare.png',
    width: 64,
    height: 64,
    source: 'official.trade2-data',
    origin: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQ3VycmVuY3lVcGdyYWRlVG9SYXJlIiwic2NhbGUiOjEsInJlYWxtIjoicG9lMiJ9XQ/9b80b44821/CurrencyUpgradeToRare.png',
  },
  'Art/2DItems/Currency/CurrencyUpgradeToUnique': {
    file: 'CurrencyUpgradeToUnique.png',
    width: 64,
    height: 64,
    source: 'official.trade2-data',
    origin: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQ3VycmVuY3lVcGdyYWRlVG9VbmlxdWUiLCJzY2FsZSI6MSwicmVhbG0iOiJwb2UyIn1d/93c6cc8d5b/CurrencyUpgradeToUnique.png',
  },
  'Art/2DItems/Currency/CurrencyUpgradeMagicToRare': {
    file: 'CurrencyUpgradeMagicToRare.png',
    width: 64,
    height: 64,
    source: 'official.trade2-data',
    origin: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQ3VycmVuY3lVcGdyYWRlTWFnaWNUb1JhcmUiLCJzY2FsZSI6MSwicmVhbG0iOiJwb2UyIn1d/e8fb148e80/CurrencyUpgradeMagicToRare.png',
  },
  'Art/2DItems/Currency/AnnullOrb': {
    file: 'AnnullOrb.png',
    width: 48,
    height: 48,
    source: 'official.trade2-data',
    origin: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQW5udWxsT3JiIiwic2NhbGUiOjEsInJlYWxtIjoicG9lMiJ9XQ/2daba8ccca/AnnullOrb.png',
  },
  'Art/2DItems/Currency/CurrencyVaal': {
    file: 'CurrencyVaal.png',
    width: 64,
    height: 64,
    source: 'official.trade2-data',
    origin: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQ3VycmVuY3lWYWFsIiwic2NhbGUiOjEsInJlYWxtIjoicG9lMiJ9XQ/72bc84396c/CurrencyVaal.png',
  },
  'Art/2DItems/Currency/FracturingOrb': {
    file: 'FracturingOrb.png',
    width: 64,
    height: 64,
    source: 'official.trade2-data',
    origin: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvRnJhY3R1cmluZ09yYiIsInNjYWxlIjoxLCJyZWFsbSI6InBvZTIifV0/8b85ed1dc2/FracturingOrb.png',
  },
  'Art/2DItems/Currency/CurrencyAddEquipmentSocket': {
    file: 'CurrencyAddEquipmentSocket.png',
    width: 64,
    height: 64,
    source: 'official.trade2-data',
    origin: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQ3VycmVuY3lBZGRFcXVpcG1lbnRTb2NrZXQiLCJzY2FsZSI6MSwicmVhbG0iOiJwb2UyIn1d/5131fd4774/CurrencyAddEquipmentSocket.png',
  },
  'Art/2DItems/Currency/CurrencyDuplicate': {
    file: 'CurrencyDuplicate.png',
    width: 64,
    height: 64,
    source: 'official.trade2-data',
    origin: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQ3VycmVuY3lEdXBsaWNhdGUiLCJzY2FsZSI6MSwicmVhbG0iOiJwb2UyIn1d/26bc31680e/CurrencyDuplicate.png',
  },
  'Art/2DItems/Currency/Omens/VoodooOmens1Yellow': {
    file: 'VoodooOmens1Yellow.png',
    width: 64,
    height: 64,
    source: 'official.trade2-data',
    origin: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvT21lbnMvVm9vZG9vT21lbnMxWWVsbG93Iiwic2NhbGUiOjEsInJlYWxtIjoicG9lMiJ9XQ/22d9b6478d/VoodooOmens1Yellow.png',
  },
  'Art/2DItems/Currency/Omens/OmenOnExaltAddExistingModType': {
    file: 'OmenOnExaltAddExistingModType.png',
    width: 64,
    height: 64,
    source: 'official.trade2-data',
    origin: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvT21lbnMvT21lbk9uRXhhbHRBZGRFeGlzdGluZ01vZFR5cGUiLCJzY2FsZSI6MSwicmVhbG0iOiJwb2UyIn1d/298d666008/OmenOnExaltAddExistingModType.png',
  },
  'Art/2DItems/Currency/Omens/OmenOnExaltConsumeQuality': {
    file: 'OmenOnExaltConsumeQuality.png',
    width: 64,
    height: 64,
    source: 'official.trade2-data',
    origin: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvT21lbnMvT21lbk9uRXhhbHRDb25zdW1lUXVhbGl0eSIsInNjYWxlIjoxLCJyZWFsbSI6InBvZTIifV0/ca4d0db767/OmenOnExaltConsumeQuality.png',
  },
  'Art/2DItems/Currency/Omens/VoodooOmens2Dark': {
    file: 'VoodooOmens2Dark.png',
    width: 64,
    height: 64,
    source: 'official.trade2-data',
    origin: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvT21lbnMvVm9vZG9vT21lbnMyRGFyayIsInNjYWxlIjoxLCJyZWFsbSI6InBvZTIifV0/0cfa6959be/VoodooOmens2Dark.png',
  },
  'Art/2DItems/Currency/Omens/VoodooOmens3Purple': {
    file: 'VoodooOmens3Purple.png',
    width: 64,
    height: 64,
    source: 'official.trade2-data',
    origin: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvT21lbnMvVm9vZG9vT21lbnMzUHVycGxlIiwic2NhbGUiOjEsInJlYWxtIjoicG9lMiJ9XQ/d901658529/VoodooOmens3Purple.png',
  },
  'Art/2DItems/Currency/Omens/VoodooOmens2Purple': {
    file: 'VoodooOmens2Purple.png',
    width: 64,
    height: 64,
    source: 'official.trade2-data',
    origin: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvT21lbnMvVm9vZG9vT21lbnMyUHVycGxlIiwic2NhbGUiOjEsInJlYWxtIjoicG9lMiJ9XQ/b9eaf38592/VoodooOmens2Purple.png',
  },
  'Art/2DItems/Currency/Omens/OmenOnRegalAddExistingModType': {
    file: 'OmenOnRegalAddExistingModType.png',
    width: 64,
    height: 64,
    source: 'official.trade2-data',
    origin: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvT21lbnMvT21lbk9uUmVnYWxBZGRFeGlzdGluZ01vZFR5cGUiLCJzY2FsZSI6MSwicmVhbG0iOiJwb2UyIn1d/314f84e4dd/OmenOnRegalAddExistingModType.png',
  },
  'Art/2DItems/Currency/Omens/VoodooOmens3Red': {
    file: 'VoodooOmens3Red.png',
    width: 64,
    height: 64,
    source: 'official.trade2-data',
    origin: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvT21lbnMvVm9vZG9vT21lbnMzUmVkIiwic2NhbGUiOjEsInJlYWxtIjoicG9lMiJ9XQ/9cfdcc9e1a/VoodooOmens3Red.png',
  },
  'Art/2DItems/Currency/Essence/FireEssence': {
    file: 'FireEssence.png',
    width: 64,
    height: 64,
    source: 'official.trade2-data',
    origin: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvRXNzZW5jZS9GaXJlRXNzZW5jZSIsInNjYWxlIjoxLCJyZWFsbSI6InBvZTIifV0/add6c12f64/FireEssence.png',
  },
  'Art/2DItems/Currency/Essence/ColdEssence': {
    file: 'ColdEssence.png',
    width: 64,
    height: 64,
    source: 'official.trade2-data',
    origin: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvRXNzZW5jZS9Db2xkRXNzZW5jZSIsInNjYWxlIjoxLCJyZWFsbSI6InBvZTIifV0/73d9fd8619/ColdEssence.png',
  },
  'Art/2DItems/Currency/Essence/LightningEssence': {
    file: 'LightningEssence.png',
    width: 64,
    height: 64,
    source: 'official.trade2-data',
    origin: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvRXNzZW5jZS9MaWdodG5pbmdFc3NlbmNlIiwic2NhbGUiOjEsInJlYWxtIjoicG9lMiJ9XQ/2c3725fdad/LightningEssence.png',
  },
  'Art/2DItems/Currency/Essence/PhysicalEssence': {
    file: 'PhysicalEssence.png',
    width: 64,
    height: 64,
    source: 'official.trade2-data',
    origin: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvRXNzZW5jZS9QaHlzaWNhbEVzc2VuY2UiLCJzY2FsZSI6MSwicmVhbG0iOiJwb2UyIn1d/e52cd05eeb/PhysicalEssence.png',
  },
  'Art/2DItems/Currency/Essence/SpeedEssence': {
    file: 'SpeedEssence.png',
    width: 64,
    height: 64,
    source: 'official.trade2-data',
    origin: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvRXNzZW5jZS9TcGVlZEVzc2VuY2UiLCJzY2FsZSI6MSwicmVhbG0iOiJwb2UyIn1d/affda36f07/SpeedEssence.png',
  },
  'Art/2DItems/Currency/Essence/CriticalEssence': {
    file: 'CriticalEssence.png',
    width: 64,
    height: 64,
    source: 'official.trade2-data',
    origin: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvRXNzZW5jZS9Dcml0aWNhbEVzc2VuY2UiLCJzY2FsZSI6MSwicmVhbG0iOiJwb2UyIn1d/febf231da7/CriticalEssence.png',
  },
  'Art/2DItems/Currency/Essence/AttackEssence': {
    file: 'AttackEssence.png',
    width: 64,
    height: 64,
    source: 'official.trade2-data',
    origin: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvRXNzZW5jZS9BdHRhY2tFc3NlbmNlIiwic2NhbGUiOjEsInJlYWxtIjoicG9lMiJ9XQ/3cece29e19/AttackEssence.png',
  },
  'Art/2DItems/Currency/Essence/LifeEssence': {
    file: 'LifeEssence.png',
    width: 64,
    height: 64,
    source: 'official.trade2-data',
    origin: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvRXNzZW5jZS9MaWZlRXNzZW5jZSIsInNjYWxlIjoxLCJyZWFsbSI6InBvZTIifV0/638d6c4cbe/LifeEssence.png',
  },
  'Art/2DItems/Currency/Breach/BreachCatalystLife': {
    file: 'BreachCatalystLife.png',
    width: 64,
    height: 64,
    source: 'official.trade2-data',
    origin: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQnJlYWNoL0JyZWFjaENhdGFseXN0TGlmZSIsInNjYWxlIjoxLCJyZWFsbSI6InBvZTIifV0/06ec489870/BreachCatalystLife.png',
  },
  'Art/2DItems/Currency/Breach/BreachCatalystMana': {
    file: 'BreachCatalystMana.png',
    width: 64,
    height: 64,
    source: 'official.trade2-data',
    origin: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQnJlYWNoL0JyZWFjaENhdGFseXN0TWFuYSIsInNjYWxlIjoxLCJyZWFsbSI6InBvZTIifV0/61d3a7a832/BreachCatalystMana.png',
  },
  'Art/2DItems/Currency/Breach/BreachCatalystDefences': {
    file: 'BreachCatalystDefences.png',
    width: 64,
    height: 64,
    source: 'official.trade2-data',
    origin: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQnJlYWNoL0JyZWFjaENhdGFseXN0RGVmZW5jZXMiLCJzY2FsZSI6MSwicmVhbG0iOiJwb2UyIn1d/568ca70b04/BreachCatalystDefences.png',
  },
  'Art/2DItems/Currency/Breach/BreachCatalystAttack': {
    file: 'BreachCatalystAttack.png',
    width: 64,
    height: 64,
    source: 'official.trade2-data',
    origin: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQnJlYWNoL0JyZWFjaENhdGFseXN0QXR0YWNrIiwic2NhbGUiOjEsInJlYWxtIjoicG9lMiJ9XQ/ccc363f502/BreachCatalystAttack.png',
  },
  'Art/2DItems/Currency/Breach/BreachCatalystCaster': {
    file: 'BreachCatalystCaster.png',
    width: 64,
    height: 64,
    source: 'official.trade2-data',
    origin: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQnJlYWNoL0JyZWFjaENhdGFseXN0Q2FzdGVyIiwic2NhbGUiOjEsInJlYWxtIjoicG9lMiJ9XQ/51dc6bc317/BreachCatalystCaster.png',
  },
  'Art/2DItems/Currency/Breach/BreachCatalystSpeed': {
    file: 'BreachCatalystSpeed.png',
    width: 64,
    height: 64,
    source: 'official.trade2-data',
    origin: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQnJlYWNoL0JyZWFjaENhdGFseXN0U3BlZWQiLCJzY2FsZSI6MSwicmVhbG0iOiJwb2UyIn1d/14b5db3c3c/BreachCatalystSpeed.png',
  },
  'Art/2DItems/Currency/Breach/BreachCatalystAttribute': {
    file: 'BreachCatalystAttribute.png',
    width: 64,
    height: 64,
    source: 'official.trade2-data',
    origin: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQnJlYWNoL0JyZWFjaENhdGFseXN0QXR0cmlidXRlIiwic2NhbGUiOjEsInJlYWxtIjoicG9lMiJ9XQ/015f6c9ac8/BreachCatalystAttribute.png',
  },
  'Art/2DItems/Currency/Runes/FireRune': {
    file: 'FireRune.png',
    width: 64,
    height: 64,
    source: 'official.trade2-data',
    origin: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvUnVuZXMvRmlyZVJ1bmUiLCJzY2FsZSI6MSwicmVhbG0iOiJwb2UyIn1d/eeabf0e7a0/FireRune.png',
  },
  'Art/2DItems/Currency/Runes/ColdRune': {
    file: 'ColdRune.png',
    width: 64,
    height: 64,
    source: 'official.trade2-data',
    origin: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvUnVuZXMvQ29sZFJ1bmUiLCJzY2FsZSI6MSwicmVhbG0iOiJwb2UyIn1d/499bfe179a/ColdRune.png',
  },
  'Art/2DItems/Currency/Runes/LightningRune': {
    file: 'LightningRune.png',
    width: 64,
    height: 64,
    source: 'official.trade2-data',
    origin: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvUnVuZXMvTGlnaHRuaW5nUnVuZSIsInNjYWxlIjoxLCJyZWFsbSI6InBvZTIifV0/98319b3998/LightningRune.png',
  },
  'Art/2DItems/Currency/Runes/EnhanceRune': {
    file: 'EnhanceRune.png',
    width: 64,
    height: 64,
    source: 'official.trade2-data',
    origin: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvUnVuZXMvRW5oYW5jZVJ1bmUiLCJzY2FsZSI6MSwicmVhbG0iOiJwb2UyIn1d/cfeb426ee0/EnhanceRune.png',
  },
  'Art/2DItems/Currency/Runes/LifeRune': {
    file: 'LifeRune.png',
    width: 64,
    height: 64,
    source: 'official.trade2-data',
    origin: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvUnVuZXMvTGlmZVJ1bmUiLCJzY2FsZSI6MSwicmVhbG0iOiJwb2UyIn1d/a09dcb651b/LifeRune.png',
  },
  'Art/2DItems/Currency/Runes/ManaRune': {
    file: 'ManaRune.png',
    width: 64,
    height: 64,
    source: 'official.trade2-data',
    origin: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvUnVuZXMvTWFuYVJ1bmUiLCJzY2FsZSI6MSwicmVhbG0iOiJwb2UyIn1d/4be6331480/ManaRune.png',
  },
  'Art/2DItems/Currency/Runes/AccuracyRune': {
    file: 'AccuracyRune.png',
    width: 64,
    height: 64,
    source: 'official.trade2-data',
    origin: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvUnVuZXMvQWNjdXJhY3lSdW5lIiwic2NhbGUiOjEsInJlYWxtIjoicG9lMiJ9XQ/8e7841f0ef/AccuracyRune.png',
  },
};
